In [1]:
import pandas as pd
import os
import sqlite3
import sys
from sqlite3 import Error

# sys.path.append('../')
from constants import *
from data_validation_checks import *
from city_tier_mapping import *
from significant_categorical_level import *
from utils import *

In [2]:
print(DB_PATH)
print(DB_FILE_NAME)
print(DATA_DIRECTORY)
print(INTERACTION_MAPPING)

utils_output.db

interaction_mapping.csv

In [3]:
build_dbs()

DB Already Exists
/Users/varunssharma/codepro-mlops-assignment/Assignment/01_data_pipeline/scripts/unit_test

'DB Exists'

In [4]:
load_data_into_db()

loaded_data already populated

In [5]:
map_city_tier()

city_tier_mapped already populated

In [6]:
map_categorical_vars()

categorical_variables_mapped already Stored

In [7]:
interactions_mapping()

model_input and interactions_mapped already stored

In [8]:
from test_with_pytest import *

In [9]:
!pip install pytest

Requirement already satisfied: pytest in /Users/varunssharma/.pyenv/versions/3.7.12/lib/python3.7/site-packages (7.4.4)
Requirement already satisfied: iniconfig in /Users/varunssharma/.pyenv/versions/3.7.12/lib/python3.7/site-packages (from pytest) (2.0.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /Users/varunssharma/.pyenv/versions/3.7.12/lib/python3.7/site-packages (from pytest) (1.2.0)
Requirement already satisfied: tomli>=1.0.0; python_version < "3.11" in /Users/varunssharma/.pyenv/versions/3.7.12/lib/python3.7/site-packages (from pytest) (2.0.1)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /Users/varunssharma/.pyenv/versions/3.7.12/lib/python3.7/site-packages (from pytest) (6.7.0)
Requirement already satisfied: packaging in /Users/varunssharma/.pyenv/versions/3.7.12/lib/python3.7/site-packages (from pytest) (23.2)
Requirement already satisfied: exceptiongroup>=1.0.0rc8; python_version < "3.11" in /Users/varunssharma/.pyenv/versions/3.7.12/lib/python3.7/site-packages (from pytest) (1.2.0)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /Users/varunssharma/.pyenv/versions/3.7.12/lib/python3.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest) (4.7.1)
Requirement already satisfied: zipp>=0.5 in /Users/varunssharma/.pyenv/versions/3.7.12/lib/python3.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest) (3.15.0)
WARNING: You are using pip version 20.1.1; however, version 23.3.2 is available.
You should consider upgrading via the '/Users/varunssharma/.pyenv/versions/3.7.12/bin/python3.7 -m pip install --upgrade pip' command.

In [10]:
print(UNIT_TEST_DB_FILE_NAME)

unit_test_cases.db

In [11]:
test_load_data_into_db()

DB Already Exists
/Users/varunssharma/codepro-mlops-assignment/Assignment/01_data_pipeline/scripts/unit_test
loaded_data already populated

In [12]:
connection = sqlite3.connect(DB_PATH + DB_FILE_NAME)
df = pd.read_sql('select * from loaded_data', connection)

In [13]:
df

,created_date,city_mapped,first_platform_c,first_utm_medium_c,first_utm_source_c,total_leads_droppped,referred_lead,1_on_1_industry_mentorship,call_us_button_clicked,career_assistance,...,specilization_click,syllabus,syllabus_expand,syllabus_submodule_expand,tab_career_assistance,tab_job_opportunities,tab_student_support,view_programs_page,whatsapp_chat_click,app_complete_flag
0,2021-11-19 15:25:38,ghazipur,Level3,Level0,Level0,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,1
1,2021-08-24 15:17:20,murbad,Level3,Level0,Level0,2.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,1
2,2021-07-20 16:01:20,mumbai,Level14,Level2,Level2,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,0
3,2021-09-04 14:00:42,bengaluru,Level7,Level0,Level0,4.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,1
4,2022-01-13 05:41:45,ncr,Level8,Level16,Level2,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-01-19 11:18:46,None,Level2,Level2,Level2,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,0
96,2021-12-12 14:14:12,banka,Level2,Level18,Level2,2.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,0
97,2021-09-07 15:44:36,None,Level1,Level19,Level4,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,0
98,2022-01-16 15:38:15,chennai,Level0,Level11,Level2,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,1
99,2021-11-12 07:02:01,ncr,Level0,Level1,Level1,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,0

In [14]:
connection.close()
connection = sqlite3.connect(UNIT_TEST_DB_FILE_NAME)
ref_df = pd.read_sql('select * from loaded_data_test_case order by created_date, city_mapped', connection)

In [15]:
ref_df

,created_date,city_mapped,first_platform_c,first_utm_medium_c,first_utm_source_c,total_leads_droppped,referred_lead,1_on_1_industry_mentorship,call_us_button_clicked,career_assistance,...,specilization_click,syllabus,syllabus_expand,syllabus_submodule_expand,tab_career_assistance,tab_job_opportunities,tab_student_support,view_programs_page,whatsapp_chat_click,app_complete_flag
0,2021-07-01 07:32:25,mumbai,Level3,Level31,Level16,2.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,1
1,2021-07-05 04:26:31,mumbai,Level2,Level6,Level7,2.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,0
2,2021-07-08 11:28:20,ncr,Level7,Level3,Level6,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,1
3,2021-07-11 05:39:39,gopalganj,Level3,Level0,Level0,4.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,1
4,2021-07-12 16:56:30,hyderabad,Level3,Level0,Level0,6.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-02-02 13:57:52,kochi,Level8,Level13,Level11,4.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,1
96,2022-02-09 07:14:35,hyderabad,Level7,Level2,Level2,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,0
97,2022-02-10 08:28:30,lucknow,Level0,Level1,Level1,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,0
98,2022-02-11 09:00:25,bengaluru,Level26,Level13,Level11,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,0
99,2022-02-11 09:50:05,ncr,Level0,Level4,Level2,3.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,1

In [16]:
test_map_city_tier()

DB Already Exists
/Users/varunssharma/codepro-mlops-assignment/Assignment/01_data_pipeline/scripts/unit_test
loaded_data already populated
city_tier_mapped already populated

In [17]:
test_map_categorical_vars()

DB Already Exists
/Users/varunssharma/codepro-mlops-assignment/Assignment/01_data_pipeline/scripts/unit_test
loaded_data already populated
city_tier_mapped already populated
categorical_variables_mapped already Stored

In [18]:
test_interactions_mapping()

DB Already Exists
/Users/varunssharma/codepro-mlops-assignment/Assignment/01_data_pipeline/scripts/unit_test
loaded_data already populated
city_tier_mapped already populated
categorical_variables_mapped already Stored
model_input and interactions_mapped already stored